### PR TITLE
Document generator for rules

### PR DESCRIPTION
**Pull request by ryuichis**
Basically with the changes incorporated in this pull request, we are able to generate the [rules section](https://github.com/oclint/oclint-docs/tree/master/rules) of [oclint documents](https://github.com/oclint/oclint-docs).

Identifier and other metadata are now part of rule implementation, and will be exposed in the doc more explicitly, hope this would lift the earlier confusions about rule name, identifier, file name, etc.

The generated docs will be also be archived as snapshots, and build machine will upload the artifacts along with oclint binary for future references.

@UnrealQuester if you are available, would you please provide a review, and provide your feedback? Thanks.

Other comments are also welcomed.

### CODE REVIEW

**Comment by UnrealQuester** [comment]
Awesome, looks great!

Is there a reason why only some rules have enableSuppress set to true? As far as I know the suppress annotation works for every rule.

**Comment by ryuichis** [comment]
Thanks @UnrealQuester. Yeah, suppress annotation is technically available to all rules. However, we only officially support a subset of rules, and leave the rest as a hidden gem. When I say "officially", it means if any users report an issue by using it, we will take a look and address that. On the contrary, for rules like `SwitchStatementsShouldHaveDefaultRule` and `InvertedLogicRule`, they might either have no where to put this annotation nor it's slightly confusing where to put it. For these cases, I prefer using the comment based suppressing (`//!OCLINT`).

**Comment by UnrealQuester** [comment]
Ah, I see.
LGTM then.

**Comment by ryuichis** [comment]
Great, thanks for the feedback, @UnrealQuester.

**Pull request merged**
