### PR TITLE
[WIP] Add travis CI integration

### PR DESCRIPTION
**Pull request by UnrealQuester**
The build takes forever on travis. Will check back on it tomorrow.

### CODE REVIEW

**Comment by ryuichis** [comment]
@UnrealQuester Thanks for the beginning of it. I took a look at Travis. And looks like the first hour or so is spent on building llvm/clang. I will work on a dedicated script for travis ci that uses prebuilt llvm/clang instead. Will ping you once I finish it.

**Comment by UnrealQuester** [comment]
@ryuichis Thanks!

**Comment by ryuichis** [comment]
@UnrealQuester I am merging this, and I have modified a travis ci configuration file based on what you have in this pull request. Please feel free to open another P.R. with your changes to .travis.yml, thanks.

**Comment by ryuichis** [comment]
@UnrealQuester looks like the build passes on Ubuntu, but takes forever for Mac. Seems Travis CI's Mac infrastructure is not as good as the linux one. I will call it a day for now. Look forward to your suggestions.

**Pull request merged**
