### PR TITLE
Formatting consistency and a few tweaks

### PR DESCRIPTION
**Pull request by vinyldarkscratch**

### CODE REVIEW

**Comment by ryuichis** [comment]
@vinyldarkscratch may I know the value introduced by formatting the entire project from one convention to another convention? I like what you have in 6cfe4dc commit, can you make it a pull request only with that?

**Comment by ryuichis** [comment]
In 7627a92, `enableGlobalAnalysis` is arguably reasonable to be added to the .oclint file. I don't see a need for the others, since they are basically for CLI. Could you cherry-pick you change, and only add support for `enableGlobalAnalysis`?

**Comment by ryuichis** [comment]
I am closing this one for now, and look forward to the pull requests that each does one thing respectively. Thanks for the hard work, @vinyldarkscratch

**Comment by vinyldarkscratch** [comment]
So I hadn't gotten notified about your last three comments and that you closed this pull request until now.  -_-  Sorry for the lack of response, and yeah, I can definitely cherry-pick both of those commits!  One quick moment while I take care of those.  ;)

As for the formatting from one convention to another, it's not a change that impacts the code's runtime, but I feel that it helps for readability of the code.  I noticed that a good portion of code in this repository followed a different formatting convention than the rest (most likely pulls from other's forks), and the sudden changes in the formatting were jarring when I was reading through.  (Plus, I'm one to prefer open curly braces on the same line as the function declarations, ifs/elseifs/elses, fors/whiles, switches, etc. even though I probably should have formatted it based upon the format used by the majority of code.  😛)  So really, it's more of an internal consistency thing, but I'll leave it out unless you'd like it!

**Pull request closed without merging**
