### PR TITLE
Fix scaffoldRule

### PR DESCRIPTION
**Pull request by LiVincent-Zhang**
The original scaffoldRule script can not generate correct cmakefile of test.

### CODE REVIEW

**Comment by LiVincent-Zhang** [comment]
Can this pr be merged now?

**Comment by LiVincent-Zhang** [comment]
@ryuichis Have you invited me to join the organization or just automatically invited?

**Comment by ryuichis** [comment]
@LiVincent-Zhang thanks for working on this. I was waiting for the travis ci to finish its builds. And yes, I sent out an invitation to you. All contributors will be added to that list, which are all copyright holders of this open source project.

**Comment by LiVincent-Zhang** [comment]
@ryuichis Thanks, I hope I could make more contributions to this project.

**Comment by ryuichis** [comment]
@LiVincent-Zhang you are definitely welcome, and look forward to future pull requests.

**Pull request merged**
